import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import NavBar from '@/components/topNavbar'
import NotesMain from '@/components/notesMain'
import NotesGrid from '@/components/notesGrid'
import { useState } from 'react'
import LoginCheck from './auth/loginCheck'
import NoteOperations from '@/components/NoteOperations'
import NoteDetails from '@/components/NoteDetails.tsx'
import { UseAuthContext } from '@/context/AuthUserProvider'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // h-[calc(100vh_-_4rem)]
  const { authUser, loading, signOut } = UseAuthContext();

  const [ID, setID] = useState<string | null>(null);
  const getSingleNote = (id: string) => {
    setID(id);
  };

  return (
    <>
      <Head>
        <title>Notes App w/firebase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex flex-col h-screen w-screen'>
        {/* <NavBar /> */}
        <div className='flex flex-row justify-between p-4 w-full h-[calc(100vh_-_4rem)]'>
          {/* <NotesMain /> */}
          <div className='w-80'>
            <p>{authUser?.email}</p>
            {/* <LoginCheck /> */}
            <NoteOperations getSingleNote={getSingleNote} />
          </div>
          <div className=''>
            <NoteDetails ID={ID} />
          </div>

          {/* <NotesGrid notesArray={[]} /> */}

        </div>
      </div>
    </>
  )
}
